version: "3.6"

services:
  ecochain:
    image: ecochainfyp/ecochain
    volumes:
      - ~/ecochain-docker/config.ini:/usr/src/app/config.ini
    #devices:
    # - /dev/gpiomem:/dev/gpiomem # for raspberry pi's GPIO
    tty: true
    restart: unless-stopped

  dashboard:
    image: ecochainfyp/ecochain-dash
    network_mode: host
    volumes:
      - ~/ecochain-docker/config.ini:/usr/src/app/config.ini
    tty: true
    restart: unless-stopped
    depends_on:
      - ecochain
